/**
 * Cornix の工場出荷時配列(tasks.json P8-3)。
 *
 * 出典: Cornix を持っている人が工場出荷時の状態を Vial で書き出して公開しているファイル
 * (oklahomer/cornix-keymap の vendor/cornix-default-keymap.vil、2026-09-30 取得。docs/keyboards/cornix.md)。
 * キーコードを、キーの一覧(key-palette.ts)と同じ表示用の名前に直した。
 * - レイヤー0 通常(QWERTY)、1(数字など)、2・3(Bluetooth の接続先の切り替え。USER00〜02 = RMK の BT0〜2)
 * - レイヤー4 以降は割り当てがないため含めない(レイヤー0 の右親指「レイヤー4(押している間)」の先は空)
 * - ダイヤル: 左は回すと音量・押すとミュート、右は回すとスクロール・押すと中クリック(全レイヤー共通)
 *   Vial の encoder_layout は [左回し, 右回し] の順。
 */

import type { Layer } from "@/lib/schemas";

export const cornixFactoryDefaultLayers: Layer[] = [
  {
    layerNumber: 0,
    layerName: "通常",
    assignments: [
      { elementId: "L-0-0", action: "press", label: "Tab" },
      { elementId: "L-0-1", action: "press", label: "Q" },
      { elementId: "L-0-2", action: "press", label: "W" },
      { elementId: "L-0-3", action: "press", label: "E" },
      { elementId: "L-0-4", action: "press", label: "R" },
      { elementId: "L-0-5", action: "press", label: "T" },
      { elementId: "L-1-0", action: "press", label: "Caps Lock" },
      { elementId: "L-1-1", action: "press", label: "A" },
      { elementId: "L-1-2", action: "press", label: "S" },
      { elementId: "L-1-3", action: "press", label: "D" },
      { elementId: "L-1-4", action: "press", label: "F" },
      { elementId: "L-1-5", action: "press", label: "G" },
      { elementId: "L-2-0", action: "press", label: "Shift" },
      { elementId: "L-2-1", action: "press", label: "Z" },
      { elementId: "L-2-2", action: "press", label: "X" },
      { elementId: "L-2-3", action: "press", label: "C" },
      { elementId: "L-2-4", action: "press", label: "V" },
      { elementId: "L-2-5", action: "press", label: "B" },
      { elementId: "L-KNOB", action: "press", label: "ミュート" },
      { elementId: "L-3-0", action: "press", label: "Ctrl" },
      { elementId: "L-3-1", action: "press", label: "Win" },
      { elementId: "L-3-2", action: "press", label: "Alt" },
      { elementId: "L-3-3", action: "press", label: "レイヤー1(押している間)" },
      { elementId: "L-3-4", action: "press", label: "レイヤー3(押している間)" },
      { elementId: "L-3-5", action: "press", label: "Space" },
      { elementId: "R-0-0", action: "press", label: "BackSpace" },
      { elementId: "R-0-1", action: "press", label: "P" },
      { elementId: "R-0-2", action: "press", label: "O" },
      { elementId: "R-0-3", action: "press", label: "I" },
      { elementId: "R-0-4", action: "press", label: "U" },
      { elementId: "R-0-5", action: "press", label: "Y" },
      { elementId: "R-1-0", action: "press", label: "Enter" },
      { elementId: "R-1-1", action: "press", label: "\\" },
      { elementId: "R-1-2", action: "press", label: "L" },
      { elementId: "R-1-3", action: "press", label: "K" },
      { elementId: "R-1-4", action: "press", label: "J" },
      { elementId: "R-1-5", action: "press", label: "H" },
      { elementId: "R-KNOB", action: "press", label: "中クリック" },
      { elementId: "R-2-0", action: "press", label: "/" },
      { elementId: "R-2-1", action: "press", label: "↑" },
      { elementId: "R-2-2", action: "press", label: "." },
      { elementId: "R-2-3", action: "press", label: "," },
      { elementId: "R-2-4", action: "press", label: "M" },
      { elementId: "R-2-5", action: "press", label: "N" },
      { elementId: "R-3-0", action: "press", label: "→" },
      { elementId: "R-3-1", action: "press", label: "↓" },
      { elementId: "R-3-2", action: "press", label: "←" },
      { elementId: "R-3-3", action: "press", label: "レイヤー2(押している間)" },
      { elementId: "R-3-4", action: "press", label: "レイヤー4(押している間)" },
      { elementId: "R-3-5", action: "press", label: "Space" },
      { elementId: "L-KNOB", action: "cw", label: "音量+" },
      { elementId: "L-KNOB", action: "ccw", label: "音量−" },
      { elementId: "R-KNOB", action: "cw", label: "ホイール↓" },
      { elementId: "R-KNOB", action: "ccw", label: "ホイール↑" },
    ],
  },
  {
    layerNumber: 1,
    layerName: "レイヤー1",
    assignments: [
      { elementId: "L-0-0", action: "press", label: "Esc" },
      { elementId: "L-0-1", action: "press", label: "1" },
      { elementId: "L-0-2", action: "press", label: "2" },
      { elementId: "L-0-3", action: "press", label: "3" },
      { elementId: "L-0-4", action: "press", label: "4" },
      { elementId: "L-0-5", action: "press", label: "5" },
      { elementId: "L-1-4", action: "press", label: ";" },
      { elementId: "L-1-5", action: "press", label: "-" },
      { elementId: "L-KNOB", action: "press", label: "ミュート" },
      { elementId: "R-0-0", action: "press", label: "Del" },
      { elementId: "R-0-1", action: "press", label: "0" },
      { elementId: "R-0-2", action: "press", label: "9" },
      { elementId: "R-0-3", action: "press", label: "8" },
      { elementId: "R-0-4", action: "press", label: "7" },
      { elementId: "R-0-5", action: "press", label: "6" },
      { elementId: "R-1-4", action: "press", label: "'" },
      { elementId: "R-1-5", action: "press", label: "=" },
      { elementId: "R-KNOB", action: "press", label: "中クリック" },
      { elementId: "L-KNOB", action: "cw", label: "音量+" },
      { elementId: "L-KNOB", action: "ccw", label: "音量−" },
      { elementId: "R-KNOB", action: "cw", label: "ホイール↓" },
      { elementId: "R-KNOB", action: "ccw", label: "ホイール↑" },
    ],
  },
  {
    layerNumber: 2,
    layerName: "レイヤー2",
    assignments: [
      { elementId: "L-1-0", action: "press", label: "Bluetooth 1" },
      { elementId: "L-2-0", action: "press", label: "Bluetooth 2" },
      { elementId: "L-KNOB", action: "press", label: "ミュート" },
      { elementId: "L-3-0", action: "press", label: "Bluetooth 3" },
      { elementId: "R-KNOB", action: "press", label: "中クリック" },
      { elementId: "L-KNOB", action: "cw", label: "音量+" },
      { elementId: "L-KNOB", action: "ccw", label: "音量−" },
      { elementId: "R-KNOB", action: "cw", label: "ホイール↓" },
      { elementId: "R-KNOB", action: "ccw", label: "ホイール↑" },
    ],
  },
  {
    layerNumber: 3,
    layerName: "レイヤー3",
    assignments: [
      { elementId: "L-1-0", action: "press", label: "Bluetooth 1" },
      { elementId: "L-2-0", action: "press", label: "Bluetooth 2" },
      { elementId: "L-KNOB", action: "press", label: "ミュート" },
      { elementId: "L-3-0", action: "press", label: "Bluetooth 3" },
      { elementId: "R-KNOB", action: "press", label: "中クリック" },
      { elementId: "L-KNOB", action: "cw", label: "音量+" },
      { elementId: "L-KNOB", action: "ccw", label: "音量−" },
      { elementId: "R-KNOB", action: "cw", label: "ホイール↓" },
      { elementId: "R-KNOB", action: "ccw", label: "ホイール↑" },
    ],
  },
];
